<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit27b17fd2c20dabf2ea56e4a83a2355a0
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DLXPlugins\\PatternWrangler\\' => 27,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DLXPlugins\\PatternWrangler\\' => 
        array (
            0 => __DIR__ . '/../..' . '/php',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit27b17fd2c20dabf2ea56e4a83a2355a0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit27b17fd2c20dabf2ea56e4a83a2355a0::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit27b17fd2c20dabf2ea56e4a83a2355a0::$classMap;

        }, null, ClassLoader::class);
    }
}
